/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Woodtotem': RouteRecordInfo<'/Woodtotem', '/Woodtotem', Record<never, never>, Record<never, never>>,
    '/woodtotems/1': RouteRecordInfo<'/woodtotems/1', '/woodtotems/1', Record<never, never>, Record<never, never>>,
    '/woodtotems/2': RouteRecordInfo<'/woodtotems/2', '/woodtotems/2', Record<never, never>, Record<never, never>>,
    '/woodtotems/3': RouteRecordInfo<'/woodtotems/3', '/woodtotems/3', Record<never, never>, Record<never, never>>,
    '/WoodtotemShow': RouteRecordInfo<'/WoodtotemShow', '/WoodtotemShow', Record<never, never>, Record<never, never>>,
  }
}
